<?xml version="1.0" encoding="utf-8"?>
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Import Project="$(VCTargetsPath)\Microsoft.Cpp.Default.props" />
  <PropertyGroup Label="Configuration">
    <ConfigurationType>Application</ConfigurationType>
    <PlatformToolset>v143</PlatformToolset>
    <CharacterSet>Unicode</CharacterSet>
    <UseDebugLibraries Condition="'$(Configuration)'=='Debug'">true</UseDebugLibraries>
    <UseDebugLibraries Condition="'$(Configuration)'=='Release'">false</UseDebugLibraries>
    <WholeProgramOptimization Condition="'$(Configuration)'=='Release'">true</WholeProgramOptimization>
  </PropertyGroup>
  <Import Project="$(VCTargetsPath)\Microsoft.Cpp.props" />
  <PropertyGroup>
    <OutDir>$(LOCALAPPDATA)\HttpCurrencyServerBuild\bin\$(Platform)\$(Configuration)\</OutDir>
    <IntDir>$(LOCALAPPDATA)\HttpCurrencyServerBuild\obj\$(MSBuildProjectName)\$(Platform)\$(Configuration)\</IntDir>
    <VcpkgEnabled>false</VcpkgEnabled>
  </PropertyGroup>
  <ItemDefinitionGroup>
    <ClCompile>
      <WarningLevel>Level4</WarningLevel>
      <SDLCheck>true</SDLCheck>
      <ConformanceMode>true</ConformanceMode>
      <LanguageStandard>stdcpp20</LanguageStandard>
      <AdditionalOptions>/utf-8 %(AdditionalOptions)</AdditionalOptions>
      <PreprocessorDefinitions>WIN32_LEAN_AND_MEAN;NOMINMAX;_CONSOLE;%(PreprocessorDefinitions)</PreprocessorDefinitions>
      <AdditionalIncludeDirectories>$(MSBuildThisFileDirectory)..\common;%(AdditionalIncludeDirectories)</AdditionalIncludeDirectories>
    </ClCompile>
    <Link>
      <SubSystem>Console</SubSystem>
      <GenerateDebugInformation>true</GenerateDebugInformation>
      <AdditionalDependencies>ws2_32.lib;%(AdditionalDependencies)</AdditionalDependencies>
    </Link>
  </ItemDefinitionGroup>
  <ItemGroup>
    <ClCompile Include="$(MSBuildThisFileDirectory)..\apps\currency-service\$(MSBuildProjectName).cpp" />
    <ClCompile Include="$(MSBuildThisFileDirectory)..\common\ApplicationSupport.cpp" />
    <ClCompile Include="$(MSBuildThisFileDirectory)..\common\CurrencyProtocol.cpp" />
    <ClCompile Include="$(MSBuildThisFileDirectory)..\common\SocketTransport.cpp" />
    <ClInclude Include="$(MSBuildThisFileDirectory)..\common\ApplicationSupport.h" />
    <ClInclude Include="$(MSBuildThisFileDirectory)..\common\CurrencyProtocol.h" />
    <ClInclude Include="$(MSBuildThisFileDirectory)..\common\SocketTransport.h" />
  </ItemGroup>
  <ItemGroup Condition="'$(ApplicationRole)'=='Server'">
    <ClCompile Include="$(MSBuildThisFileDirectory)..\common\CurrencyCatalog.cpp" />
    <ClCompile Include="$(MSBuildThisFileDirectory)..\common\CurrencyServerService.cpp" />
    <ClInclude Include="$(MSBuildThisFileDirectory)..\common\CurrencyCatalog.h" />
    <ClInclude Include="$(MSBuildThisFileDirectory)..\common\CurrencyServerService.h" />
  </ItemGroup>
  <ItemGroup Condition="'$(ApplicationRole)'=='Client'">
    <ClCompile Include="$(MSBuildThisFileDirectory)..\common\CurrencyClientService.cpp" />
    <ClInclude Include="$(MSBuildThisFileDirectory)..\common\CurrencyClientService.h" />
  </ItemGroup>
  <Import Project="$(VCTargetsPath)\Microsoft.Cpp.targets" />
</Project>
